### ISSUE TITLE
Thermal strain quantities (EPTH) not exposed via direct API in PyDPF-Post

### ISSUE THREAD

**Issue by vnamdeo** [ansys/pydpf-post#481]
### Description of the feature

Thermal strain results are available in DPF Simulation Model and it's also listed in the available results, however, no direct APIs exposed in PyDPF Post in order to extract it. 

It will be nice, if we could support all results quantities are available in Simulation Model should be exposed via direct API in order to extract it. 

Please refer attached images for reference.
![dpf_1](https://github.com/ansys/pydpf-post/assets/126097319/97e47183-d198-4e4f-9278-5d0c7fc0f678)
![dpf_2](https://github.com/ansys/pydpf-post/assets/126097319/710a8c4a-3d78-473a-8912-b70548402a15)

### Steps for implementing the feature

Perform any structural thermal simulation to see the thermal strain quantities.

### Useful links and references

NA

**Comment by PProfizi** [comment]
Hi @vnamdeo,
Thank you for this enhancement request. 
Our result APIs for SImulation objects are indeed not complete yet. We focused on some main ones but we are definitely going to add all of them as time goes on.
We also have planned to offer a "generic" result extraction API so that people may ask for any result that would not yet be exposed.
I'll look into adding the thermal ones and will be linking my PR to this issue.
