### ISSUE TITLE
Version selector not working in 0.6.0 stable doc

### ISSUE THREAD

**Issue by PProfizi** [ansys/pydpf-post#525]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/index.html#compatibility) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

https://post.docs.pyansys.com/version/stable/

See version selector on top-right

### Steps To Reproduce

NA

### Which Operating System are you using?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version are you using?

3.7

### Installed packages

NA

**Comment by PProfizi** [comment]
@Revathyvenugopal162 any idea what went wrong?

**Comment by Revathyvenugopal162** [comment]
@PProfizi  for me the drop down menu is working as expected , in dark mode the styles has to improve, because it is in very light color for me, 
![image](https://github.com/ansys/pydpf-post/assets/104772255/b8f25780-1e00-4ae2-9d2d-b23aef85cfb1)
i checked in edge and in chrome. Isnt it the same version switcher you are mentioning?

**Comment by PProfizi** [comment]
@Revathyvenugopal162 ah indeed it now works! I guess it took some time to update. Sorry about that! Thx!
