### ISSUE TITLE
DPF-RST file compatibility

### ISSUE THREAD

**Issue by agrishin** [ansys/pydpf-post#577]
### Description of the modifications

Costas Vogiatzis (Costas.Vogiatzis@Honeywell.com) asks the following:

"From a Python script I get the error below when attempting to access RST data from DPF. I was under the impression that one could use DPF to access RST files from earlier ANSYS versions. Can you please clarify how DPF version compatibility works specifically in accessing RST files?

Python Error: InvalidANSYSVersionError: Ansys v202 does not support DPF

Regards,

Costas Vogiatzis
Aero & Mechanical Sciences
Honeywell Aerospace Technologies"

**Comment by PProfizi** [comment]
Hi @agrishin,

Yes, DPF can indeed read RST files emanating from older ANSYS versions, the same way MAPDL can.
The issue encountered here is due to the fact that DPF as a tool did not exist before ANSYS v211 as you can see [here](https://dpf.docs.pyansys.com/version/stable/getting_started/index.html#install-dpf-server) and [here](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1).

PyDPF libraries are client libraries which need a DPF server installation to connect to.
It seems like here your client is trying to use PyDPF with an ANSYS 2020R2, which does not include DPF.

What you can do if bumping to a more recent isntallation of ANSYS is not possible, is install a DPF server as a standalone application as explained [here](https://dpf.docs.pyansys.com/version/stable/user_guide/getting_started_with_dpf_server.html).

**Comment by agrishin** [comment]
Thanks! Customer has been notified. I think we can consider this issue closed...
